services:
    nimble_elastic.client_factory:
        class: Nimble\ElasticBundle\Client\ClientFactory
        calls:
            - [setContainer, [@service_container]]

    nimble_elastic.client_prototype:
        abstract: true
        factory:
            - @nimble_elastic.client_factory
            - createClient

    nimble_elastic.index_manager:
        class: Nimble\ElasticBundle\Index\IndexManager

    nimble_elastic.synchronizer_manager:
        class: Nimble\ElasticBundle\Synchronizer\SynchronizerManager

    nimble_elastic.transformer_manager:
        class: Nimble\ElasticBundle\Transformer\TransformerManager

    nimble_elastic.populator_manager:
        class: Nimble\ElasticBundle\Populator\PopulatorManager
        arguments:
            - @nimble_elastic.transformer_manager

    nimble_elastic.doctrine.orm.listener:
        class: Nimble\ElasticBundle\Doctrine\ORM\LifecycleEventSubscriber
        arguments:
            - @nimble_elastic.synchronizer_manager

