services:
    nimble_elastic.client_factory:
        class: Nimble\ElasticBundle\Client\ClientFactory

    nimble_elastic.client_prototype:
        abstract: true
        class: Elasticsearch\Client
        factory:
            - @nimble_elastic.client_factory
            - createClient
        arguments:
            - []

    nimble_elastic.index_manager:
        class: Nimble\ElasticBundle\Index\IndexManager

    nimble_elastic.synchronizer_manager:
        class: Nimble\ElasticBundle\Synchronizer\SynchronizerManager

    nimble_elastic.transformer_manager:
        class: Nimble\ElasticBundle\Transformer\TransformerManager

    nimble_elastic.doctrine.orm.listener:
        class: Nimble\ElasticBundle\Doctrine\ORM\LifecycleEventSubscriber
        arguments:
            - @nimble_elastic.synchronizer_manager

    nimble_elastic.synchronizer.prototype:
        abstract: true
        class: Nimble\ElasticBundle\Synchronizer\Synchronizer
        arguments:
            - null
            - null
            - null
            - null
            - null
            - @nimble_elastic.transformer_manager